### ISSUE TITLE
アプリ＞出荷　使用品番に数字を入れると完了が押せなくなる

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/osa-web#10]
品番は、大文字アルファベットA-Z と 数字。
小文字で押せなるなるのはgoodだと思います。
ただ、今は数字もアウトになっています。

加えて、入力時に最初からシフト２連打状態(caps lock)の状態にできないでしょうか？

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。アップデートでご確認ください。

**Comment by take-iwa** [comment]
確認しました。
