### ISSUE TITLE
工程内の作業管理

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/osa-web#17]
洗浄に出された筬でも、全ての洗浄作業が必要な場合と簡単な洗浄で済む場合があります。

したがって、工程(ステータス)内での作業を入力する部分が必要です。

(ex. 　洗浄　有 / 無

**Comment by take-iwa** [comment]
@alexeypolitov 作業リストフォーマット
https://docs.google.com/spreadsheets/d/1w315jpdPiG8o86q_p3-Y5UOD7H9vRT3LPbJPa3A6oJ0/edit?usp=sharing

**Comment by take-iwa** [comment]
@alexeypolitov 作業リストは、pdfの方だと思うのですが、カラムがずれています。
「作業リスト」は不要。

ファイル名は、`作業リスト_<出力日時>.pdf`

それと、枠が太すぎるので線にしてもらいたいです。
[59c0d985adbcd.pdf](https://github.com/DecodeLLC/osa-web/files/1313759/59c0d985adbcd.pdf)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
