### ISSUE TITLE
おさ詳細画面について

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/osa-web#19]
１）おさ詳細>使用年月日
表示これで合ってます？編集ボタン押してない状態でこれなのですが。
<img width="237" alt="osa" src="https://user-images.githubusercontent.com/23730555/30901496-0830845e-a3a3-11e7-895e-802455513c80.png">
工程登録後
<img width="231" alt="osa" src="https://user-images.githubusercontent.com/23730555/30901739-01cc6bc2-a3a4-11e7-8637-542acbb1c38a.png">

２）おさ詳細>仕様
選択肢の文言修正
コミカル→`コニカル`
<img width="252" alt="osa" src="https://user-images.githubusercontent.com/23730555/30901444-c7aca21e-a3a2-11e7-8541-81593f7afed9.png">

**Comment by alexeypolitov** [comment]
@take-iwa 
1. 変更しました。こちらの項目は自動で登録されてます
2. 変更しました
