### ISSUE TITLE
筬一覧での表示内容

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/osa-web#9]
筬一覧での表示フィールドは、以下を表示してほしいです
　　・オサ番号（タイトル）
　　・タイプ（WJ or AJ）
　　・使用品番
　　・羽数
　　・有効幅
　　・所有工場
　　・現在の工程

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。アップデートでご確認ください。

**Comment by take-iwa** [comment]
確認しました。
